ingress_public_hostnames:
  - kompassi.eu
  - conit.fi

backup_ingress_public_hostnames:
  - vara.kompassi.eu

postgres_managed: false
postgres_hostname: siilo.tracon.fi
postgres_database: kompassi
postgres_username: kompassi
postgres_ssl: true

redis_managed: false
redis_hostname: redis-ha-haproxy.redis-ha.svc.cluster.local
redis_broker_database: 9
redis_cache_database: 9

kompassi_secret_managed: false
kompassi_storage_pvc: false
kompassi_storage_pvc_storageclass: longhorn-nfs
kompassi_installation_name: Kompassi
kompassi_installation_slug: turska
kompassi_base_url: https://kompassi.eu
kompassi_v2_base_url: https://v2.kompassi.eu
kompassi_tickets_v2_api_url: http://uvicorn.kompassi-production.svc.cluster.local:7998
kompassi_admins:
  - Luka Pajukanta <santtu@pajukanta.fi>
kompassi_allowed_hosts: !Concat
  - !Var ingress_public_hostnames
  - !Var backup_ingress_public_hostnames

kompassi_cors_allowed_hosts: []
# empty for now as all queries are done server to server. feel free to add sites if necessary
# - v2.kompassi.eu
# # "just in case", ask Knome
# - wp.ropecon.fi
# - ropecon.fi

# TODO this list should probably be autogenerated from the list of Kompassi OIDC clients
# https://kompassi.eu/admin/oauth2_provider/application/
kompassi_csp_allowed_login_redirects:
  - "*.tracon.fi"
  - "*.con2.fi"
  - "*.ropecon.fi"
  - "*.kompassi.eu"
  - "*.solmukohta.eu"
  - "*.kotae.fi"
  - "conikuvat.fi"
  - "larppikuvat.fi"
  - "ropekonsti.fi"
  - "larpit.fi"

kompassi_readiness_probe: !Void
kompassi_liveness_probe: !Void
kompassi_workers: 12

smtp_server: sr1.pahaip.fi
smtp_default_from_email: suunnistajat@kompassi.eu

setup_should_run: true

ingress_letsencrypt_enabled: true
ingress_letsencrypt_cluster_issuer: letsencrypt-prod

minio_bucket_name: kompassi
minio_endpoint_url: https://minio.con2.fi
