# kompassi deployment using Kubernetes
# usage: emrichen kubernetes.in.yml | kubectl apply -n kompassi -f -

!Include defaults.in.yml


#########
# REDIS #
#########
---
!If
  test: !Var redis_managed
  then: !Include redis/service.in.yml

---
!If
  test: !Var redis_managed
  then: !Include redis/deployment.in.yml

---
!If
  test: !All [!Var redis_managed, !Var redis_storage_pvc]
  then: !Include redis/pvc.in.yml


##############
# POSTGRESQL #
##############
---
!If
  test: !Var postgres_managed
  then: !Include postgres/service.in.yml

---
!If
  test: !Var postgres_managed
  then: !Include postgres/deployment.in.yml

---
!If
  test: !Var postgres_managed
  then: !Include postgres/pvc.in.yml

---
!If
  test: !Var postgres_managed
  then: !Include postgres/secret.in.yml


#########################
# GUNICORN (Web server) #
#########################
---
!Include kompassi/service.in.yml
---
!Include kompassi/deployment.in.yml
---
!If
  test: !Var kompassi_storage_pvc
  then: !Include kompassi/pvc.in.yml
---
!Include kompassi/secret.in.yml


##############################
# CELERY (Background worker) #
##############################
---
!Include celery/deployment.in.yml


###############################
# NGINX (Static file serving) #
###############################
---
!Include nginx/service.in.yml
---
!Include nginx/deployment.in.yml


###########
# INGRESS #
###########
---
!Include ingress.in.yml
