# Kompassi deployment using Kubernetes
# usage: emrichen kubernetes.in.yml | kubectl apply -n kompassi -f -

!Include defaults.in.yml


#############
# MEMCACHED #
#############
---
!If
  test: !Var memcached_managed
  then: !Include memcached/service.in.yml
---
!If
  test: !Var memcached_managed
  then: !Include memcached/deployment.in.yml


############
# RABBITMQ #
############
---
!If
  test: !Var rabbitmq_managed
  then: !Include rabbitmq/service.in.yml

---
!If
  test: !Var rabbitmq_managed
  then: !Include rabbitmq/deployment.in.yml

---
!If
  test: !Var rabbitmq_managed
  then: !Include rabbitmq/pvc.in.yml

---
!If
  test: !Var rabbitmq_managed
  then: !Include rabbitmq/secret.in.yml


##############
# POSTGRESQL #
##############
---
!If
  test: !Var postgres_managed
  then: !Include postgres/service.in.yml

---
!If
  test: !Var postgres_managed
  then: !Include postgres/deployment.in.yml

---
!If
  test: !Var postgres_managed
  then: !Include postgres/pvc.in.yml

---
!If
  test: !Var postgres_managed
  then: !Include postgres/secret.in.yml


#########################
# GUNICORN (Web server) #
#########################
---
!Include kompassi/service.in.yml
---
!Include kompassi/deployment.in.yml
---
!Include kompassi/pvc.in.yml
---
!Include kompassi/secret.in.yml


##############################
# CELERY (Background worker) #
##############################
---
!Include celery/deployment.in.yml


###############################
# NGINX (Static file serving) #
###############################
---
!Include nginx/service.in.yml
---
!Include nginx/deployment.in.yml


###########
# INGRESS #
###########
---
!Include ingress.in.yml


##################
# DATABASE SETUP #
##################
---
!If
  test: !Var setup_should_run
  then: !Include jobs/setup.in.yml
