apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    stack: kompassi
    component: postgres
  annotations: !If
    test: !Var postgres_password
    then: !Void
    else:
      secret-generator.v1.mittwald.de/autogenerate: password
type: Opaque
data:
  username: !Base64 ,Var postgres_username
  hostname: !Base64 ,Var postgres_hostname
  database: !Base64 ,Var postgres_database
  password: !If
    test: !Var postgres_password
    then: !Base64 ,Var postgres_password
