name: cicd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      SKAFFOLD_DEFAULT_REPO: ghcr.io/con2
    steps:
      - uses: actions/checkout@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - id: cache-bin
        uses: actions/cache@v3
        with:
          path: bin
          key: ${{ runner.os }}-bin
      - if: steps.cache-bin.outputs.cache-hit != 'true'
        run: |
          mkdir bin
          curl -Lo bin/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x bin/skaffold

      - uses: docker/setup-buildx-action@v1
      - id: build
        run: |
          bin/skaffold build --file-output build.json
      - name: Store build.json artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-json
          path: build.json

  deploy_staging:
    runs-on: self-hosted
    needs: build
    environment: Staging
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v3
        with:
          name: build-json
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - id: cache-bin
        uses: actions/cache@v3
        with:
          path: bin
          key: ${{ runner.os }}-bin
      - if: steps.cache-bin.outputs.cache-hit != 'true'
        run: |
          mkdir bin
          curl -Lo bin/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x bin/skaffold

      - uses: docker/setup-buildx-action@v1
      - run: |
          npm ci
          cd kubernetes && ENV=staging npx ts-node manifest.ts && cd ..
          skaffold deploy -n kompassi2-staging -a build.json

  deploy_production:
    runs-on: self-hosted
    needs: build
    environment: Production
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v3
        with:
          name: build-json
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - id: cache-bin
        uses: actions/cache@v3
        with:
          path: bin
          key: ${{ runner.os }}-bin
      - if: steps.cache-bin.outputs.cache-hit != 'true'
        run: |
          mkdir bin
          curl -Lo bin/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x bin/skaffold

      - uses: docker/setup-buildx-action@v1
      - run: |
          npm ci
          cd kubernetes && ENV=production npx ts-node manifest.ts && cd ..
          skaffold deploy -n kompassi2-production -a build.json
